# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :ios_beta_app do
    build_app(
      scheme: "Runner",
      archive_path: "./build/Runner.xcarchive",
      export_method: "development",
      output_directory: "./build/Runner"
  )
    firebase_app_distribution(
      app: "1:435028589225:ios:f25ee85f52dacce77387b8",
      testers: "zacky@rumahkisah.id, yazid.al2418@gmail.com",
      release_notes: "Update Version Number Name And Code",
      firebase_cli_path: "/usr/local/bin/firebase",
      ipa_path: "./build/Runner/Runner.ipa"
  )
    increment_version_number(
      xcodeproj: "/Users/yazidalghazali/Flutter/developer/flutter_fastlane/ios/Runner.xcodeproj"
    )
    increment_build_number(
      xcodeproj: "/Users/yazidalghazali/Flutter/developer/flutter_fastlane/ios/Runner.xcodeproj" # (optional, you must specify the path to your main Xcode project if it is not in the project root directory)
  ) 
    # add actions here: https://docs.fastlane.tools/actions
  end
end
