# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do |options|
    desc "Build Apk"
    build_number = last_git_tag()
    Dir.chdir '../..' do
      sh('flutter', 'clean')
      sh('flutter', 'pub', 'get')
      sh('flutter', 'build', 'apk', '--release', "--build-number=#{build_number.to_i}")
    end
  next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
  build_number = next_version
    firebase_app_distribution(
      app: "1:435028589225:android:9224ce79f031a4237387b8",
      testers: "yazid.al2418@gmail.com",
      release_notes: build_number.to_s,
      firebase_cli_path: "/usr/local/bin/firebase",
      apk_path: "../build/app/outputs/apk/release/app-release.apk"
  )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :android_beta_app do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
