# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :android_test_app do
    gradle(task: "test")
    firebase_app_distribution(
      app: "1:435028589225:android:9224ce79f031a4237387b8",
      testers: "yazid.al2418@gmail.com",
      release_notes: "",
      firebase_cli_path: "/usr/local/bin/firebase",
      apk_path: "../build/app/outputs/apk/release/app-release.apk"
  )
    changelog_from_git_commits( 
      pretty: "- (%ae) %s",
      date_format: "short",
      match_lightweight_tag: false,  
      merge_commit_filtering: "exclude_merges" 
  )
  changelog_from_git_commits
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :android_beta_app do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
